# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 19134541549885fd42726a738e4c356393add318973c0db6f09c2084773848e075cb4bef1cdfddafa1805fda842b4ff2743d652a542d3ce1ad2853f0b74e5534

test:
  secret_key_base: ef9ba4ea9ca17b78ad8dd0495a27b70517d526b09b90e7988b6db92d4721aa937b325f3f7471331b3ab0a6ea67fc41ff2cb54575567e2226b1abb059e61e1992

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
